version: '2'
services:
    test51-app:
        image: test51
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://test51-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=test51
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    test51-mongodb:
        extends:
            file: mongodb.yml
            service: test51-mongodb
